### ISSUE TITLE
confuse about the paper

### ISSUE THREAD

**Issue by seanM29** [chenbinghui1/ECAML#1]
for metric learning(like re-id, image retrieval), we want intra-class distance small, and the inter-class distance large.
but Energy Confusion term want  the feature distributions from different classes closer, it seems opposite  of the goal, which makes me confused
Thank you for sharing results of your work.
This is a really impressive paper and your response is appreciated.

**Comment by chenbinghui1** [comment]
@seanM29  I recommend to read again the paper, why we use the confusion term has been detailed discussed in paper.
